# Numpy :

In [177]:
# NumPy stands for Numerical Python. NumPy is a Python library used for working with arrays.
!pip install numpy

In [179]:
import numpy as np  # importing numpy

# creating numpy
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)], dtype=float)
c=np.array([[(1.5,2.5,3),(5,6,7)],[(4,6,9),(0,8,6)]], dtype=float)

print(a)
print(b)
print(c)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
[[[1.5 2.5 3. ]
  [5.  6.  7. ]]

 [[4.  6.  9. ]
  [0.  8.  6. ]]]


### Initial placeholders -

In [47]:
# creating an array of zeroes.

np.zeros((3,4))  # creating 2D array - '3' rows and '4' columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
# creating an array of ones

np.ones((3,5,6))  # creating 2D array with '3' times '5' rows and '6' columns

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [57]:
# creating an array of evenly spaced values ( step value )

evenly_spaced=np.arange(21,52,5) # steps n-1 = (5-1=4) and range between 21 and 52
print(evenly_spaced)

[21 26 31 36 41 46 51]


In [69]:
# creating an array of evenly spaced values ( number of samples )

np.linspace(10,100,7) # this will split the numbers between 0 and 8 with 7 elements. 

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [107]:
# creating a constant array.( 1D )

constant_array=np.full((12),21)   # ((columns),value)
print(constant_array)  
print('No of dimensions : ',constant_array.ndim)   # to find number of dimensions

[21 21 21 21 21 21 21 21 21 21 21 21]
No of dimensions :  1


In [105]:
# creating 2D array

array_2d=np.full((4,6),21)  # ((rows,columns),value)
print(array_2d)
print('No of dimensions : ',array_2d.ndim)

[[21 21 21 21 21 21]
 [21 21 21 21 21 21]
 [21 21 21 21 21 21]
 [21 21 21 21 21 21]]
No of dimensions :  2


In [163]:
# creating 3D array

array_3d=np.full((2,5,6),21)  # ((repeat,rows,columns),value)
print(array_3d)
print('No of dimensions : ',array_3d.ndim)

[[[21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]]

 [[21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]
  [21 21 21 21 21 21]]]
No of dimensions :  3


In [179]:
# creating 3D array

array_3d=np.full((2,5,6), 'lle')  # ((repeat,rows,columns),value)
print(array_3d)
print('No of dimensions : ',array_3d.ndim)

[[['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']]

 [['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']
  ['lle' 'lle' 'lle' 'lle' 'lle' 'lle']]]
No of dimensions :  3


In [113]:
# creating an identity natrix.

f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [121]:
# create an array with random numbers.

np.random.random((4,3))

array([[0.68395818, 0.437638  , 0.52328563],
       [0.22203424, 0.04778182, 0.74343491],
       [0.14468264, 0.80688591, 0.16800212],
       [0.02131357, 0.5468215 , 0.10088718]])

In [129]:
# to print random number between given numbers.

np.random.randint(10,100)

70

In [139]:
# To find shape of an array & size of an array.

arr=np.array([[3,4,5,2],[4,5,6,7],[2,3,4,5],[3,6,8,4],[3,9,0,3]])
print(arr.shape)
print(arr.size)

(5, 4)
20


In [153]:
# To find length of an array.

arr=np.array([[2,4,6],[6,4,2],[0,0,0],[1,1,1],[2,3,4],[4,7,9]])
len(arr)

6

In [220]:
# To find length of an array.

arr=np.array([[2,'r',True],[2.46,'e','f']])
len(arr)

2

### Access Array Elements - 

In [181]:
# we can access any array element with respect to its index number
import pandas as pd

arr=pd.array([3,5,7,12,34])  # 1D  array
print(arr[4])

34


In [183]:
# using arthemetic operations on elements with the help of index.

num=pd.array([18,22,34,19,21,2])

sum = num[0]+num[2]
sub = num[2]-num[1]
multi = num[1]*num[3]
divi = num[1]/num[0]
modulo = num[4]%num[2]
expo = num[2]**num[5]
floor_divi = num[3]//num[0]

print(sum,sub,multi,divi,modulo,expo,floor_divi , sep='\n')

52
12
418
1.2222222222222223
21
1156
1


In [640]:
# accessing 2D array

arr=np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

print(arr[3,2])

8


In [646]:
# accessing 3D array
mat = np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]],
                 [[4,5,6,7],[5,6,7,8],[6,7,8,9]],
                 [[7,8,9,0],[8,9,0,1],[9,0,1,2]]])
print(mat[1,2,3])

9


### Data Types -

In [192]:
# 'i'-integer, 'b'-boolean, 'u'-unsigned integer, 'f'-flaot, 'c'-complex float , 'M'-datetime, 'O'-object , 'S'-string 

arr = np.array([2,4,6,8])
print(arr)
print(arr.dtype)

[2 4 6 8]
int32


In [194]:
arr = np.array([2,4,6,8], dtype='S')
print(arr)
print(arr.dtype)

[b'2' b'4' b'6' b'8']
|S1


In [196]:
arr = np.array([2,4,6,8], dtype='i4')
print(arr)
print(arr.dtype)

[2 4 6 8]
int32


In [198]:
# changing datatype from float to integer using 'i' as parameter value.
arr=np.array([2.3,3.4,2.0,1.9,6.8])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[2 3 2 1 6]
int32


In [208]:
# changing datatype from float to integer.
arr=np.array([2.3,3.4,2.0,1.9,6.8])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[2 3 2 1 6]
int32


In [210]:
# changing datatype from int to bool.
arr=np.array([1,2,3,4])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool


### copy() method -

In [254]:
original = np.array([1,3,5,7,9])
copy = original.copy()

original[1] = 21 # modifing the element in the array

print(copy)
print(original)

[1 3 5 7 9]
[ 1 21  5  7  9]


### view() 

In [266]:
matrix = np.array([9,8,7,6,5,4,3,2,1])
mat=matrix.view()

matrix[2] = 21

print(mat)
print(matrix)

[ 9  8 21  6  5  4  3  2  1]
[ 9  8 21  6  5  4  3  2  1]


In [272]:
arr = np.array([[1,2,3,4],[4,3,2,1]])
print(arr.shape) # to know the no.of rows and columns

(2, 4)


### Reshaping Arrays -

In [317]:
# Reshaping means changing the shape an array.

# converting 1D array into 2D array.

array_1D = np.array([1,2,3,4,5,6,7,8])
print(array_1D.size)

array_2D = array_1D.reshape(4,2)
print(array_2D)

8
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [333]:
# Coverting 1D array into 3D array.

array_1D = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_1D.size)

array_3D = array_1D.reshape(2,1,5) # (repetition,rows,columns)
print(array_3D)

10
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [353]:
# converting 2D array into 3D array.

array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D.size)

array_3D = array_2D.reshape(2,2,2)  # (repetition,rows,columns)
print(array_3D)

8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [365]:
# converting 3D array into 2D array.

array_3D = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(array_3D.size)

array_2D = array_3D.reshape(4,4)  # (repetition,rows,columns)
print(array_2D)

16
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [367]:
# converting 3D array into 1D array.

array_3D = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(array_3D.size)

array_1D = array_3D.reshape(16)  # (repetition,rows,columns)
print(array_1D)

16
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [369]:
# converting 2D array into 1D array.

array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D.size)

array_1D = array_2D.reshape(8)  # (repetition,rows,columns)
print(array_1D)

8
[1 2 3 4 5 6 7 8]


### Python program to create a data type object 

In [462]:
# creating an object.

A = np.array([[1,2],[3,4]] , dtype=np.float64)
B = np.array([[8,6],[7,8]] , dtype=np.float64)

In [478]:
# performing an arthematic operations on the object create to an array.

sum = A+B
sub = A-B
multi = A*B
divi = A/B
modulo = A%B
expo = A**B
floor_divi = A//B

print(sum,sub,multi,divi,modulo,expo,floor_divi, sep=' \n\n\n ')

[[ 9.  8.]
 [10. 12.]] 


 [[-7. -4.]
 [-4. -4.]] 


 [[ 8. 12.]
 [21. 32.]] 


 [[0.125      0.33333333]
 [0.42857143 0.5       ]] 


 [[1. 2.]
 [3. 4.]] 


 [[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]] 


 [[0. 0.]
 [0. 0.]]


In [480]:
print(np.add(A,B)) # addition

[[ 9.  8.]
 [10. 12.]]


In [482]:
print(np.subtract(A,B))  #subtraction

[[-7. -4.]
 [-4. -4.]]


In [484]:
print(np.multiply(A,B))  # Multiplication

[[ 8. 12.]
 [21. 32.]]


In [486]:
print(np.divide(A,B))  # Division

[[0.125      0.33333333]
 [0.42857143 0.5       ]]


In [494]:
# both 'mod()' and 'remainder()' gives the remainder as output after division operation has done.
print(np.mod(A,B))
print(np.remainder(A,B)) # Modulo

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [496]:
# The divmod() function return both the quotient and the remainder/mod. 
# The return value is two arrays, the first array contains the quotient and second array contains the remainder/mod.

print(np.divmod(A,B)) # both divide and modulo

(array([[0., 0.],
       [0., 0.]]), array([[1., 2.],
       [3., 4.]]))


In [500]:
print(np.sqrt(A,B)) # square root

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [498]:
print(np.power(A,B)) # Power

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [532]:
# absolute() method is use to convert the negative numbers to positive numbers by removing the '-' sign.
# Here 'absolute()' and 'abs()' both methods are same. 

x = np.array([[1,-2],[-3,4]])
y = np.array([[-5,6],[7,-8]])

print(np.absolute(x))
print(np.abs(y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [544]:
#  Sort() method

arr = np.array([7,4,5,3,2,34,6,9,8,0])
print(np.sort(arr))

[ 0  2  3  4  5  6  7  8  9 34]


### Slicing -

In [548]:
# Slicing elements from index 1 to 5.

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:6])

[2 3 4 5 6]


In [562]:
# slicing element from beginning to index '3'
print(arr[:3])

[1 2 3]


In [564]:
# slicing elements from index '3' to the end of the array
print(arr[3:])

[ 4  5  6  7  8  9 10]


In [616]:
# Using the step value to determine the step of the slicing.
print(arr[1:8:2])  # [from index 1 : 8 index : 2 (skips 1 element )] - n-1 = 2-1 = 1 time/element

[2 4 6 8]


In [618]:
# returns every other element from the entire array
print(arr[::2]) # (n-1 = 2-1 =1) skips one number
print(arr[::4]) # (n-1 = 4-1 = 3) skips three numbers

[1 3 5 7 9]
[1 5 9]


In [620]:
# slicing 2D array

arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(arr[1,1:4])

[6 7 8]


In [622]:
# returns both element index '2'

arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(arr[0:3,2])

[3 7 6]


In [636]:
# slicing 3D array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])
print(arr[0,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
5


### Negative Slicing - 

In [608]:
# slicing elements from the index 5 from end to index 1 from end
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[-5:-1])

[6 7 8 9]
